version: '3.9'
services:
  tekton_challenge_api:
    container_name: tekton_challenge_api
    image: tekton_challenge_api:1.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://tekton_challenge_db:5432/tekton_challenge
      - DATABASE_USERNAME=tekton_challenge
      - DATABASE_PASSWORD=tekton_challenge_123
      - API_PERCENTAGE_BASE_URL=http://localhost:8080
    depends_on:
      - tekton_challenge_db
  tekton_challenge_db:
    container_name: tekton_challenge_db
    image: postgres:14.10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tekton_challenge
      - POSTGRES_USER=tekton_challenge
      - POSTGRES_PASSWORD=tekton_challenge_123